version: "3.9"

services:
  postgres:
    image: postgres:14.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: epro_pass
      POSTGRES_USER: epro_user
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/a_schema.sql
      - ./database/dummy_data.sql:/docker-entrypoint-initdb.d/b_dummy_data.sql